### ISSUE TITLE
pantries.models.StoreIngredient 메서드 status_ingredient 관련 질문

### ISSUE THREAD

**Issue by Hans97a** [liketoy/cookipedia-backend#8]
pantries를 admin페이지에서 만들고 ingredient를 상세 페이지에서 추가시 모델 ingredients.Ingredient의 필드값인 expiry_date가 공란일 경우 다음과 같은 에러가 발생하는데요

- in status_ingredient
    else self.date_bought + timedelta(self.ingredient.expiry_date)
TypeError: unsupported type for timedelta days component: NoneType

status_ingredient 메서드의 첫번째 if문 이후 문장에서 에러가 발생하는 것 같은데 Ingredient.expiry필드 값이 비어있는 경우를 대비해 if문으로 추가 처리 해야할까요?
`expiry_date = (
                self.expiry_date
                if self.expiry_date is not None
                else self.date_bought + timedelta(self.ingredient.expiry_date)
            )`

아니면 새로운 브랜치를 만들고 (git checkout -b feature/api/hans) 후  git pull origin develop 했더니 needs merge 에러가 떠서 혼자서 해보려고 하다 보니 develop과 신규 브랜치가 부분적으로만 pull돼서 변경사항을 수작업으로 수정했는데 여기서 문제가 발생하고 있는지 모르겠습니다..ㅠㅠ;

**Comment by bewoody** [comment]
아 거기에 에러가 있었네요! 
수정해서 다시 반영해놨습니다ㅎㅎ
1. status_ingredient 메서드에 조건을 좀 추가
2. ingredients.models.Ingredient에 expiry_date 가 null값을 받을 수가 없게 설정되어있어서 null=True 옵션을 추가

```console
$ git pull origin develop
```
